### PR TITLE
Deregister workbook saved event from workbook object when workbook closed

### LINKED ISSUE #171: Excel_Toolkit: Crashing on exit
#### Description:

Excel is hogging processes on exit and crashing, needing to force-close through task manager before re-opening Excel. 

#### How to replicate:

Run the sample script below. Be sure to check 64 bit version as this is what all users will be switched to. 

#### Expected behaviour:

Excel should close without crashing, and release all processes. 

#### Test file(s):

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Excel_Toolkit/Issues?csf=1&e=O2WO6m

### PR DESCRIPTION
**Pull request by awakeman**
### Issues addressed by this PR

Closes #171 

Seems to be the cause of excel crashing and reopening on exit. From what i can tell it looks like something comes along deregistering event handlers in the exit procedure of Excel. One of the event handlers introduced by #208 was directly on the Workbook object which then doesn't exist (or sometimes/often doesn't exist, thanks to garbage collection being non-deterministic) by the time the event handler is cleared up, leading to a "Object reference not set to an instance of an object." exception that goes unhandled. I have also moved the creation of said event handler to the first moment BHoM is used for that workbook.

### Test files

Open a new workbook, use any BHoM method from Ctrl+Shift+B or Ribbon, close the workbook.

Also if people testing can try to confirm the crash *does* happen by commenting line 46 of `ComponentManager.cs` and doesn't when this line is present using the same procedure as above.

```cs
                m_Managers[workbook.Name].Dispose();
```

### Changelog

- Fix Excel Crashing on exit bug (#171)

### CODE REVIEW

File: Excel_UI/Addin/AddIn.cs [hunk 1]
```diff
@@ -86,9 +86,11 @@ public void AutoOpen()
 
         public void AutoClose()
         {
+            // note: This method only runs if the Addin gets disabled during
+            // execution, it does not run when excel closes.
```
Comment (FraserGreenroyd) [inline Excel_UI/Addin/AddIn.cs:90]: 👍

**Comment by FraserGreenroyd** [comment]
I have tested this PR, including with commenting out the line mentioned. I do not experience any issues with Excel, however, I was not experiencing issues with Excel before either. For that reason, I am not approving this PR because I cannot confirm that the bug itself is fixed.

Please take this comment as acceptance that this PR is not making anything worse, but it would be good for @MajaLindroth @maryannewachter @BingWangUS @rwemay to confirm if the bug itself is resolved :smile:

**Review by kayleighhoude — COMMENTED** [review]
Similar to @FraserGreenroyd I wasn't experiencing the issue before, and upon testing the fix I'm not now either

**Review by maryannewachter — APPROVED** [review]
Tested with PR, no relaunch.

Tested with PR, commented out line 46 in `ComponentManager.cs`, relaunch happens if file has been open for a few minutes.

**Comment by al-fisher** [comment]
Have tested also, and although could also not recreate the bug before, this behaviour is naturally fine for me too so see no issue.

Suggesting we therefore merge based on all the positive comments and reviews. 
This will mean we will get a good number more solid days general testing in alphas across a wider pool of individuals in advance of beta next week.

Thanks @awakeman @FraserGreenroyd
